### Rota para listar as reservas
GET http://localhost:3000/reservas

###

### Rota para buscar uma reserva específica
GET http://localhost:3000/reservas/3

###


### Rota para criar reserva
POST http://localhost:3000/reservas
Content-Type: application/json

{
    "usuario":"Valtemir Lima 10",
    "sala":"C2",
    "data_horario_inicio": "18/02/2025 16:24",
    "data_horario_termino": "18/02/2025 17:24",
    "status": "reservado"
}

###

### Rota para atualizar reserva
PUT http://localhost:3000/reservas/8
Content-Type: application/json

{
    "novoHorario": "2025-03-10 17:00:00",
    "novoStatus": "cancelado"
}

###

### Roda para excluir reserva
DELETE http://localhost:3000/reservas/8
Content-Type: application/json

###



